import slicer
vol  = slicer.util.loadVolume(r"C:/Codes/Us_MRI_Fusion/PRE-TCIA/Preprocessing/pipeline_v3/preprocessed/0001_MRI_vol_iso.nii.gz")
heat = slicer.util.loadVolume(r"C:/Codes/ClaseGener/PROYECTO/test_output/0001_MRI_coarse_heatmap.nii.gz")
heat.SetName("Coarse_Heatmap_0001")
dn = heat.GetDisplayNode()
dn.SetAndObserveColorNodeID("vtkMRMLColorTableNodeFileHotToColdRainbow.txt")
dn.SetAutoWindowLevel(False)
dn.SetWindowLevelMinMax(0.05, 1.0)
dn.SetOpacity(0.6)
slicer.util.setSliceViewerLayers(background=vol, foreground=heat, foregroundOpacity=0.5)
fid = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode", "Centroid_Coarse_0001")
fid.AddControlPoint(82.5, 93.1, 42.2)
fid.GetDisplayNode().SetSelectedColor(0.2, 1.0, 0.3)
fid.GetDisplayNode().SetGlyphScale(3.0)
slicer.util.resetSliceViews()
print("Centroide coarse: (82.5,93.1,42.2) mm")
